# -*- coding: utf-8 -*-
"""random forest classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q800ibv4hxLzJl5ktd18JP364Yq6Gu2
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree
x=np.array([
    [1.5,2.0],[1.8,2.5],[2.2,3.0],[2.5,3.2],[2.8,3.8],[3.0,4.0],[3.5,4.5],[4.0,5.0],[4.2,5.2],[4.5,5.5],
    [5.0,1.0],[5.5,1.5],[6.0,2.0],[6.2,2.5],[6.5,3.0],[6.8,3.5],[7.0,4.0],[7.5,4.5],[8.0,5.0],[8.5,5.5],
    [9.0,6.0],[9.2,6.2],[9.5,6.5],[10.0,7.0],[10.5,7.5],[11.0,8.0],[11.5,8.5],[12.0,9.0],[12.5,9.5],[13.0,10.0]
])
y=np.array([
    0,0,0,0,0,0,0,0,0,0,
    1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2
])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
rf_model=RandomForestClassifier(n_estimators=5,criterion='gini',random_state=42)
rf_model.fit(x_train,y_train)
new_point=np.array([[7.0,6.0]])
predicted_class=rf_model.predict(new_point)
print(f"Predicted Class for point{new_point}:{predicted_class[0]}")
plt.figure(figsize=(12,8))
plot_tree(rf_model.estimators_[0],feature_names=["x1","x2"],class_names=["Class0","Class1","Class2"],filled=True)
plt.title("Single Decision Tree in Random Forest")
plt.show()
plt.figure(figsize=(8,6))
plt.scatter(x[:,0],x[:,1],c=y,cmap="coolwarm",edgecolors='k',label="Data Points")
plt.scatter(new_point[:,0],new_point[:,1],c='green',marker='*',s=200,label="New Point")
plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Random Forest Classification with Decision  ")
plt.legend()
plt.show()